= Design
:stylesheet: dark.css
:stylesdir: /home/kurt/asciidoctor-skins/css
:docinfodir: ./
:docinfo: shared

== Azure Translation Overview

My **kurt-text-translation** service is the pay-as-you-go **S1 Standard**. It cost (see
link:https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/[Azure AI
Translator Pricing])
$10 per million chars of standard translation.

In addtion to text translation, Document translation is supported, but it uses a different endpoint. 

=== Azure Hourly Translation Request Limits

There is an limit on how many **characters can be translated per hour**. This hourly limit is based
on your translation tier. For my **S1 pay-as-you-go** tier. The character limit oer
hour is 40 million charactes.

Azure Text Translate
link:https://learn.microsoft.com/en-us/azure/ai-services/translator/service-limits[Rate Limits]
explains how often you can request text translation:

Your character limit per hour is based on your Translator subscription tier.

The hourly quota should be consumed evenly throughout the hour. For example, at the F0 tier limit of
2 million characters per hour, characters should be consumed no faster than roughly 33,300
characters per minute. The sliding window range is 2 million characters divided by 60 minutes.

You're likely to receive an out-of-quota response under the following circumstances:

* You reached or surpassed the quota limit.
* You sent a large portion of the quota in too short a period of time.

There are no limits on concurrent requests.

[%header,width=40%,cols="1,4",frame="none",grid="rows"]
.Azure Text Translate Tier Quotas
|===
|Tier|	Character limit

|F0     
|2 million characters per hour

|S1     
|40 million characters per hour

|S2 / C2
|40 million characters per hour

|S3 / C3
|120 million characters per hour

|S4 / C4
|200 million characters per hour
|===

Limits for multi-service subscriptions are the same as the S1 tier.

These limits are restricted to Microsoft's standard translation models. Custom translation models
that use Custom Translator are limited to 3,600 characters per second, per model.

See these links

* link:https://learn.microsoft.com/en-us/answers/questions/1434488/why-has-this-azure-ai-translate-request-exceeded-r[Requests Exceeded].
* link:https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#error-code[Request Limits and Throttling]

===  Azure Text Translation Response Status Codes

See
link:https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-translate#response-status-codes[Response
Status Codes]

The following are the possible HTTP status codes that a request returns.

[caption="Azure"]
.Status codes
[%header,width=65%,cols="1,7",frame="none",grid="rows"]
|===
|Code|Description

|200
|Success.

|400
|One of the query parameters is missing or not valid. Correct request parameters before retrying.

|401
|The request couldn't be authenticated. Check that credentials are specified and valid.

|403
|The request isn't authorized. Check the details error message. This status code often indicates
that you used all the free translations provided with a trial subscription.

|408
|The request couldn't be fulfilled because a resource is missing. Check the details error message. When the request includes a custom category, this status code often indicates that the custom translation system isn't yet available to serve requests. The request should be retried after a waiting period (for example, 1 minute).

|429
|The server rejected the request because the client exceeded request limits.

|500
|An unexpected error occurred. If the error persists, report it with: date and time of the failure, request identifier from response header X-RequestId, and client identifier from request header X-ClientTraceId.

|503
|Server temporarily unavailable. Retry the request. If the error persists, report it with: date and
time of the failure, request identifier from response header X-RequestId, and client identifier from
request header X-ClientTraceId.
|===

If an error occurs, the request returns a JSON error response. The error code is a 6-digit number combining the 3-digit HTTP status code followed by a 3-digit number to further categorize the error. Common error codes can be found on the v3 Translator reference page.

== Deepl Translation Response Status Codes

See link:https://www.deepl.com/docs-api/api-access/error-handling[Error Handling]:

[quote,Deepl Error Handling]
____
Errors are indicated by standard HTTP status codes. It is important to make sure that your
application handles errors in an appropriate way. To that end, please consult the list of expected
status code results that is provided with each endpoint's documentation.
Special care should be taken to ensure proper handling of:

HTTP 429: too many requests. Your application should be configured to resend the request after some
delay, rather than constantly resending the request.

HTTP 456: quota exceeded. The translation limit of your account has been reached. Consider upgrading
your subscription.

HTTP 500 and higher: temporary errors in the DeepL service. Your application should be configured to
resend the request after some delay, rather than constantly resending the request.

If the error persists for a long time, please contact support@DeepL.com.
When retrying failed requests, your application should implement an exponential-backoff strategy:
increasing the delay time with each further failed request. All official DeepL client libraries
implement this strategy, so they can be used as a reference.
____

== Guzzle Exceptions Overview 

* The `AzureTranslator::lookup()`, the dictionary word look up, does not return the expected result;
* howerver, I am using Systran instead. Azure
should return a result(s) similiar to `SystranTranslator::lookup()`, namely, a `WordInterface` of
either `SystranNoun-`, `-Verb`, or `RelatedVerb`. 

== Guzzle Exceptions Design

According to the Guzzle
link:https://docs.guzzlephp.org/en/stable/quickstart.html?highlight=ClientException#exceptions[Exceptions]
documentation:

The following tree view describes the Guzzle Exceptions hierachy:

[,bash]
----
. \RuntimeException
└── TransferException (implements GuzzleException)
    ├── ConnectException (implements NetworkExceptionInterface)
    └── RequestException
        ├── BadResponseException
	│   ├── ServerException
        │   └── ClientException
	└── TooManyRedirectsException
----

Guzzle throws exceptions for errors that occur during a transfer.

* A `GuzzleHttp\Exception\ConnectException` exception is thrown in the event of a networking error.
* This exception extends from `GuzzleHttp\Exception\TransferException`.
* A `GuzzleHttp\Exception\ClientException` is thrown for **400** level errors if the `http_errors`
* request option is set to `true`. This exception extends from 
`GuzzleHttp\Exception\BadResponseException` and `GuzzleHttp\Exception\BadResponseException` extends
from `GuzzleHttp\Exception\RequestException`. +

[source,php]
----
use GuzzleHttp\{Psr7, Exception\ClientException};

try {

    $client->request('GET', 'https://github.com/_abc_123_404');

} catch (ClientException $e) {

    echo Psr7\Message::toString($e->getRequest());
    echo Psr7\Message::toString($e->getResponse());

    $response = $e->getResponse();

    echo "The response code is: " . $response->getStatusCode() . "\n";
}
----

* A `GuzzleHttp\Exception\ServerException` is thrown for **500** level errors if the http_errors
* request option is set to true. This exception extends from
* `GuzzleHttp\Exception\BadResponseException`.
* A `GuzzleHttp\Exception\TooManyRedirectsException` is thrown when too many redirects are followed.
* This exception extends from `GuzzleHttp\Exception\RequestException`.

All of the above exceptions extend from `GuzzleHttp\Exception\TransferException`.

== Alternate Database Schema

This is just an idea that needs to be based on D.J. Date readings. It is the SSQL chnage below:

The Database scheme change below will make all tables dependent on `words`, so when it is
deleted, all other tables likewise get deleted. It seems to make the sql 

As a result of the table alteration and the introduction of a new table, I will need to:

1. Change db.sql and drop.sql
2. Change the code so it inserts into these new tables instead of the old. 
3. And I need to change the SQL query that selects conjugations from the old scheme to
use the new scheme.

```sql
# -- The actual verb conjs are in this table
# -- prefix and reflexive verbs share the conjuation of the 
# -- main verb. Thus, the conjugation of ankommen is kommen's
# -- conjugation.
create table if not exists conjs (
  id int not null auto_increment primary key,
  conjugation varchar(75) not null
  verb_id int not null,
  foreign key(verb_id) references words(id) on delete cascade
);

# -- main verb is main_id. Prefix or reflexsive that shared its conjugation
# -- shared_id. Example: kommen, say, has words.id of 1 and ankommen has
# -- words.id of 2, then we have row with: {1, 2}
create table if not exists shared_conjs (
  shared_id int not null primary key,
  main_id int not null primary key,
  unique (main_id, shared_id),
  foreign key(main_id) references words(id) on delete cascade,
  foreign key(shared_id) references words(id) on delete cascade
);
```
